export const movieCatalog = [
  { id: 1, title: 'Shawshank Redemption', genre: 'Drama', mood: 'Hopeful', description: 'A prison drama with remarkable emotional payoff.' },
  { id: 2, title: 'The Godfather', genre: 'Crime', mood: 'Epic', description: 'A legendary family story shaped by ambition and loyalty.' },
  { id: 3, title: 'Spirited Away', genre: 'Animation', mood: 'Magical', description: 'A dreamlike adventure through a mysterious spirit world.' },
  { id: 4, title: 'Moonlight', genre: 'Drama', mood: 'Intimate', description: 'A tender story of identity, memory, and growing up.' },
  { id: 5, title: 'Parasite', genre: 'Thriller', mood: 'Sharp', description: 'A social satire that becomes tension-filled and unforgettable.' },
  { id: 6, title: 'Arrival', genre: 'Sci-Fi', mood: 'Thoughtful', description: 'A human story shaped by language, connection, and time.' },
  { id: 7, title: 'The Social Network', genre: 'Drama', mood: 'Fast', description: 'A sharp and stylish look at ambition and innovation.' },
  { id: 8, title: 'The Grand Budapest Hotel', genre: 'Comedy', mood: 'Whimsical', description: 'Stylish, funny, and pictorially rich.' },
  { id: 9, title: 'The Apartment', genre: 'Romance', mood: 'Warm', description: 'A bittersweet romantic classic with wit and heart.' },
  { id: 10, title: 'Dune', genre: 'Sci-Fi', mood: 'Epic', description: 'Big ideas and massive scale with strong visual storytelling.' },
  { id: 11, title: 'No Country for Old Men', genre: 'Thriller', mood: 'Tense', description: 'A brutal, elegant thriller with razor sharp energy.' },
  { id: 12, title: 'Lady Bird', genre: 'Coming-of-age', mood: 'Honest', description: 'A realistic, intimate portrait of growing up.' },
  { id: 13, title: 'The Dark Knight', genre: 'Action', mood: 'Electric', description: 'A morally complex superhero epic with unforgettable tension.' },
  { id: 14, title: 'Inception', genre: 'Sci-Fi', mood: 'Mind-bending', description: 'A layered thriller about dreams, memory, and obsession.' },
  { id: 15, title: 'The Matrix', genre: 'Sci-Fi', mood: 'Revolutionary', description: 'A groundbreaking cyberpunk classic about reality and control.' },
  { id: 16, title: 'Pulp Fiction', genre: 'Crime', mood: 'Stylish', description: 'A nonlinear masterpiece of cool dialogue and sharp storytelling.' },
  { id: 17, title: 'Fight Club', genre: 'Drama', mood: 'Disturbing', description: 'A raw, intense story about identity, rebellion, and masculinity.' },
  { id: 18, title: 'The Departed', genre: 'Crime', mood: 'Tense', description: 'A ruthless crime drama with layered deception and pressure.' },
  { id: 19, title: 'The Silence of the Lambs', genre: 'Thriller', mood: 'Chilling', description: 'A psychological cat-and-mouse thriller with incredible tension.' },
  { id: 20, title: 'The Prestige', genre: 'Drama', mood: 'Mystical', description: 'A brilliant illusionist story about obsession and sacrifice.' },
  { id: 21, title: 'Interstellar', genre: 'Sci-Fi', mood: 'Epic', description: 'A sweeping space odyssey about survival, love, and time.' },
  { id: 22, title: 'La La Land', genre: 'Romance', mood: 'Dreamy', description: 'A glossy, emotional musical about ambition and love.' },
  { id: 23, title: 'Whiplash', genre: 'Drama', mood: 'Intense', description: 'A high-pressure music drama about obsession and excellence.' },
  { id: 24, title: 'Forrest Gump', genre: 'Drama', mood: 'Warm', description: 'A moving, funny, and deeply human story of life and chance.' },
  { id: 25, title: 'The Green Mile', genre: 'Drama', mood: 'Emotional', description: 'A prison tale of mercy, injustice, and redemption.' },
  { id: 26, title: 'Casablanca', genre: 'Romance', mood: 'Classic', description: 'A timeless tale of love, sacrifice, and wartime choices.' },
  { id: 27, title: 'Citizen Kane', genre: 'Drama', mood: 'Inventive', description: 'A groundbreaking portrait of power, ambition, and legacy.' },
  { id: 28, title: '2001: A Space Odyssey', genre: 'Sci-Fi', mood: 'Epic', description: 'A monumental journey through evolution, time, and the unknown.' },
  { id: 29, title: 'Blade Runner 2049', genre: 'Sci-Fi', mood: 'Atmospheric', description: 'A visually stunning existential sci-fi journey.' },
  { id: 30, title: 'Mad Max: Fury Road', genre: 'Action', mood: 'Relentless', description: 'A high-speed desert chase with relentless energy.' },
  { id: 31, title: 'The Batman', genre: 'Action', mood: 'Moody', description: 'A dark, atmospheric detective thriller in superhero form.' },
  { id: 32, title: 'Avengers: Endgame', genre: 'Action', mood: 'Crowd-pleaser', description: 'Big stakes, big spectacle, and a satisfying payoff.' },
  { id: 33, title: 'The Lion King', genre: 'Animation', mood: 'Epic', description: 'A sweeping coming-of-age story about leadership and loss.' },
  { id: 34, title: 'Toy Story', genre: 'Animation', mood: 'Joyful', description: 'A charming story about friendship, imagination, and growing up.' },
  { id: 35, title: 'Finding Nemo', genre: 'Animation', mood: 'Heartfelt', description: 'A colourful, emotional journey about family and courage.' },
  { id: 36, title: 'Up', genre: 'Animation', mood: 'Heartwarming', description: 'An adventure full of wonder, grief, and love.' },
  { id: 37, title: 'Inside Out', genre: 'Animation', mood: 'Emotional', description: 'A playful and moving look at feelings and growing up.' },
  { id: 38, title: 'The Emperor’s New Groove', genre: 'Animation', mood: 'Funny', description: 'A quick, funny, and surprisingly charming comedy adventure.' },
  { id: 39, title: 'Coco', genre: 'Animation', mood: 'Emotional', description: 'A celebration of family, music, and memory.' },
  { id: 40, title: 'The Princess Bride', genre: 'Adventure', mood: 'Playful', description: 'A heartfelt fantasy story full of humour and romance.' },
  { id: 41, title: 'The Lord of the Rings: The Fellowship of the Ring', genre: 'Fantasy', mood: 'Epic', description: 'A heroic adventure of friendship, courage, and destiny.' },
  { id: 42, title: 'The Lord of the Rings: The Two Towers', genre: 'Fantasy', mood: 'Epic', description: 'A darker, larger battle for Middle-earth.' },
  { id: 43, title: 'The Lord of the Rings: The Return of the King', genre: 'Fantasy', mood: 'Triumphant', description: 'A grand finale of sacrifice, hope, and victory.' },
  { id: 44, title: 'Harry Potter and the Sorcerer’s Stone', genre: 'Fantasy', mood: 'Magical', description: 'An enchanting introduction to a world of magic and wonder.' },
  { id: 45, title: 'Harry Potter and the Prisoner of Azkaban', genre: 'Fantasy', mood: 'Atmospheric', description: 'A mysterious and emotionally rich chapter of the saga.' },
  { id: 46, title: 'The Hobbit: An Unexpected Journey', genre: 'Fantasy', mood: 'Adventure', description: 'A charming and expansive epic of courage and camaraderie.' },
  { id: 47, title: 'Pan’s Labyrinth', genre: 'Fantasy', mood: 'Dark', description: 'A beautiful, haunting fantasy set against war and loss.' },
  { id: 48, title: 'The Shape of Water', genre: 'Fantasy', mood: 'Romantic', description: 'A tender fantasy romance with mystery and wonder.' },
  { id: 49, title: 'Get Out', genre: 'Horror', mood: 'Unsettling', description: 'A razor-sharp horror film about identity and fear.' },
  { id: 50, title: 'Hereditary', genre: 'Horror', mood: 'Disturbing', description: 'A devastating and dread-filled family horror story.' },
  { id: 51, title: 'The Conjuring', genre: 'Horror', mood: 'Intense', description: 'A classic paranormal investigation with genuine scares.' },
  { id: 52, title: 'A Quiet Place', genre: 'Horror', mood: 'Tense', description: 'A nerve-shredding survival thriller with a strong emotional core.' },
  { id: 53, title: 'The Witch', genre: 'Horror', mood: 'Atmospheric', description: 'A chilling folk horror tale of fear and obsession.' },
  { id: 54, title: 'E.T. the Extra-Terrestrial', genre: 'Sci-Fi', mood: 'Nostalgic', description: 'A heartfelt story of friendship and wonder across worlds.' },
  { id: 55, title: 'Back to the Future', genre: 'Sci-Fi', mood: 'Fun', description: 'A joyfully inventive time-travel comedy adventure.' },
  { id: 56, title: 'Ex Machina', genre: 'Sci-Fi', mood: 'Mindful', description: 'A sleek, intelligent AI thriller about ethics and identity.' },
  { id: 57, title: 'The Fifth Element', genre: 'Sci-Fi', mood: 'Vivid', description: 'A visually flamboyant space adventure with a strong sense of style.' },
  { id: 58, title: 'Arrival', genre: 'Sci-Fi', mood: 'Thoughtful', description: 'A deeply emotional look at language, connection, and fate.' },
  { id: 59, title: 'District 9', genre: 'Sci-Fi', mood: 'Intense', description: 'A gritty, inventive sci-fi action story about exclusion and survival.' },
  { id: 60, title: 'Twelve Angry Men', genre: 'Drama', mood: 'Tense', description: 'A masterclass in dialogue, justice, and human bias.' },
  { id: 61, title: 'Before Sunrise', genre: 'Romance', mood: 'Intimate', description: 'A charming conversation-driven romance filled with connection and possibility.' },
  { id: 62, title: 'Before Sunset', genre: 'Romance', mood: 'Reflective', description: 'A deeply human romantic conversation about time and choices.' },
  { id: 63, title: 'The Notebook', genre: 'Romance', mood: 'Emotional', description: 'A sweeping love story with warmth and heartbreak.' },
  { id: 64, title: 'La La Land', genre: 'Romance', mood: 'Dreamy', description: 'A stylish, emotional musical about ambition and love.' },
  { id: 65, title: 'Romeo + Juliet', genre: 'Romance', mood: 'Passionate', description: 'A modern and vivid take on a classic tragic romance.' },
  { id: 66, title: 'The Favourite', genre: 'Drama', mood: 'Witty', description: 'A darkly comedic historical drama with sharp character work.' },
  { id: 67, title: 'Midsommar', genre: 'Horror', mood: 'Disorienting', description: 'A folk horror story steeped in ritual, dread, and emotional collapse.' },
  { id: 68, title: 'The Others', genre: 'Horror', mood: 'Atmospheric', description: 'A moody, elegant ghost story full of dread and uncertainty.' },
  { id: 69, title: 'The VVitch', genre: 'Horror', mood: 'Unsettling', description: 'A slow-burn folk horror with an unforgettable atmosphere.' },
  { id: 70, title: 'The Art of Racing in the Rain', genre: 'Drama', mood: 'Heartwarming', description: 'A moving story about love, family, and life’s unexpected turns.' },
  { id: 71, title: 'The Pianist', genre: 'Drama', mood: 'Intense', description: 'A brutal, tender portrait of survival amid war.' },
  { id: 72, title: 'Schindler’s List', genre: 'Drama', mood: 'Profound', description: 'A solemn, unforgettable account of humanity under extraordinary pressure.' },
  { id: 73, title: 'The Intouchables', genre: 'Comedy', mood: 'Uplifting', description: 'A warm, witty story about friendship across cultures and class.' },
  { id: 74, title: 'Life Is Beautiful', genre: 'Comedy', mood: 'Heartfelt', description: 'A profound and life-affirming story told through humour and tenderness.' },
  { id: 75, title: 'Amélie', genre: 'Romance', mood: 'Whimsical', description: 'A tender, whimsical exploration of beauty and connection.' },
  { id: 76, title: 'The Lives of Others', genre: 'Drama', mood: 'Thoughtful', description: 'A rich, layered look at surveillance, power, and conscience.' },
  { id: 77, title: 'The Room', genre: 'Drama', mood: 'Cult', description: 'A cult classic of chaotic intensity and unforgettable emotional oddity.' },
  { id: 78, title: 'The Lion in Winter', genre: 'Drama', mood: 'Historical', description: 'A sharp and dramatic depiction of power and family.' },
  { id: 79, title: 'The King’s Speech', genre: 'Drama', mood: 'Inspiring', description: 'A warm historical drama about courage, disability, and leadership.' },
  { id: 80, title: 'The Truman Show', genre: 'Comedy', mood: 'Thoughtful', description: 'A clever satire on identity, freedom, and performance.' },
  { id: 81, title: 'Good Will Hunting', genre: 'Drama', mood: 'Human', description: 'A deeply moving story of genius, trauma, and personal change.' },
  { id: 82, title: 'The Devil Wears Prada', genre: 'Comedy', mood: 'Stylish', description: 'A witty and stylish look at ambition, femininity, and work.' },
  { id: 83, title: 'The Big Lebowski', genre: 'Comedy', mood: 'Laid-back', description: 'A cult comedy with surreal charm and strange wisdom.' },
  { id: 84, title: 'Groundhog Day', genre: 'Comedy', mood: 'Thoughtful', description: 'A clever, life-affirming story about repetition and self-growth.' },
  { id: 85, title: 'Dead Poets Society', genre: 'Drama', mood: 'Inspirational', description: 'A stirring film about creativity, courage, and self-expression.' },
  { id: 86, title: 'The Breakfast Club', genre: 'Drama', mood: 'Real', description: 'A classic look at adolescence, identity, and connection.' },
  { id: 87, title: 'The Social Network', genre: 'Drama', mood: 'Fast', description: 'A sharp look at ambition, ego, and digital power.' },
  { id: 88, title: 'Memento', genre: 'Thriller', mood: 'Puzzle-box', description: 'A mind-bending noir thriller about memory and identity.' },
  { id: 89, title: 'Se7en', genre: 'Thriller', mood: 'Dark', description: 'A bleak and unforgettable serial killer mystery.' },
  { id: 90, title: 'The Usual Suspects', genre: 'Crime', mood: 'Twisty', description: 'A cat-and-mouse crime story with a famous final reveal.' },
  { id: 91, title: 'Oldboy', genre: 'Thriller', mood: 'Brutal', description: 'An intense revenge thriller with huge emotional impact.' },
  { id: 92, title: 'Drive', genre: 'Crime', mood: 'Lyrical', description: 'A neon-lit crime film with precision, cool, and emotional weight.' },
  { id: 93, title: 'Nightcrawler', genre: 'Thriller', mood: 'Creepy', description: 'A cold, stylish look at ambition and morality in the media world.' },
  { id: 94, title: 'Prisoners', genre: 'Thriller', mood: 'Gripping', description: 'A deeply unsettling mystery about desperation and moral fracture.' },
  { id: 95, title: 'The Revenant', genre: 'Adventure', mood: 'Harsh', description: 'A brutal survival epic defined by sacrifice and endurance.' },
  { id: 96, title: 'Gladiator', genre: 'Action', mood: 'Epic', description: 'An intense and grand historical action film about power and vengeance.' },
  { id: 97, title: 'The Last Samurai', genre: 'Action', mood: 'Epic', description: 'A sweeping story about honour, identity, and transformation.' },
  { id: 98, title: 'The Revenant', genre: 'Adventure', mood: 'Harsh', description: 'A brutal survival epic defined by sacrifice and endurance.' },
  { id: 99, title: 'The Departed', genre: 'Crime', mood: 'Tense', description: 'A layered crime drama of betrayal and pressure.' },
  { id: 100, title: 'The Wolf of Wall Street', genre: 'Comedy', mood: 'Wild', description: 'A riotous, indulgent high-wire business saga.' },
  { id: 101, title: 'Lagaan', genre: 'Drama', mood: 'Inspirational', description: 'An epic sports drama with strong emotional and historical gravity.' },
  { id: 102, title: '3 Idiots', genre: 'Comedy', mood: 'Heartfelt', description: 'A lively, funny, and emotionally resonant coming-of-age story.' },
  { id: 103, title: 'Dilwale Dulhania Le Jayenge', genre: 'Romance', mood: 'Warm', description: 'A beloved romantic classic of love, family, and identity.' },
  { id: 104, title: 'PK', genre: 'Comedy', mood: 'Thoughtful', description: 'A funny and moving film about belief, curiosity, and humanity.' },
  { id: 105, title: 'Bajrangi Bhaijaan', genre: 'Drama', mood: 'Uplifting', description: 'A warm-hearted adventure about compassion and humanity.' },
  { id: 106, title: 'Slumdog Millionaire', genre: 'Drama', mood: 'Energetic', description: 'A vibrant journey of survival, memory, and destiny.' },
  { id: 107, title: 'The Kashmir Files', genre: 'Drama', mood: 'Intense', description: 'A hard-hitting historical drama with emotional weight.' },
  { id: 108, title: 'Dangal', genre: 'Drama', mood: 'Inspirational', description: 'A powerful family saga about ambition, pressure, and excellence.' },
  { id: 109, title: 'Gully Boy', genre: 'Drama', mood: 'Electric', description: 'A raw, hopeful story about talent, class, and expression.' },
  { id: 110, title: 'Jawan', genre: 'Action', mood: 'Explosive', description: 'A patriotic action film with high-energy suspense.' },
  { id: 111, title: 'RRR', genre: 'Action', mood: 'Explosive', description: 'A stylized and thrilling action epic with mass appeal.' },
  { id: 112, title: 'Baahubali: The Beginning', genre: 'Action', mood: 'Epic', description: 'A visually grand action fantasy with huge emotional stakes.' },
  { id: 113, title: 'Baahubali 2: The Conclusion', genre: 'Action', mood: 'Epic', description: 'A grand finale of power, betrayal, and destiny.' },
  { id: 114, title: 'K.G.F: Chapter 1', genre: 'Action', mood: 'Intense', description: 'A stylish underworld action film with commanding energy.' },
  { id: 115, title: 'K.G.F: Chapter 2', genre: 'Action', mood: 'Explosive', description: 'A larger-than-life continuation of a gritty rise-to-power story.' },
  { id: 116, title: 'Sultan', genre: 'Sport', mood: 'Motivating', description: 'A gripping sports drama about ambition and grit.' },
  { id: 117, title: 'Kabir Singh', genre: 'Drama', mood: 'Intense', description: 'A passionate and turbulent love story with emotional extremes.' },
  { id: 118, title: 'Hichki', genre: 'Drama', mood: 'Uplifting', description: 'A warm and inspiring story about resilience and purpose.' },
  { id: 119, title: 'Aamir', genre: 'Drama', mood: 'Thoughtful', description: 'A grounded and tense drama about moral pressure and justice.' },
  { id: 120, title: 'My Name Is Khan', genre: 'Drama', mood: 'Warm', description: 'A human story about identity, prejudice, and dignity.' },
  { id: 121, title: 'Pyaasa', genre: 'Drama', mood: 'Classic', description: 'A timeless film about creativity, heartbreak, and artistic struggle.' },
  { id: 122, title: 'Anand', genre: 'Drama', mood: 'Heartfelt', description: 'A classic story of hope, humour, and life in the face of illness.' },
  { id: 123, title: 'Sholay', genre: 'Action', mood: 'Legendary', description: 'A celebrated Bollywood classic with comedy, action, and iconic characters.' },
  { id: 124, title: 'Deewar', genre: 'Crime', mood: 'Classic', description: 'A powerful crime saga about loyalty, class, and family.' },
  { id: 125, title: 'Zindagi Na Milegi Dobara', genre: 'Drama', mood: 'Free-spirited', description: 'A breezy and emotionally rich story about friendship and life.' },
  { id: 126, title: 'Brokeback Mountain', genre: 'Romance', mood: 'Melancholic', description: 'A deeply moving love story shaped by time and impossible circumstances.' },
  { id: 127, title: 'The Hurt Locker', genre: 'Action', mood: 'Intense', description: 'A high-pressure war film about adrenaline, danger, and stress.' },
  { id: 128, title: 'Fallen Angels', genre: 'Drama', mood: 'Urban', description: 'A moody and atmospheric noir story of isolation and desire.' },
  { id: 129, title: 'Spirited Away', genre: 'Animation', mood: 'Magical', description: 'A Japanese animated treasure about wonder and self-discovery.' },
  { id: 130, title: 'Your Name', genre: 'Animation', mood: 'Romantic', description: 'A heartfelt and visually stunning story of connection across time.' },
  { id: 131, title: 'Weathering with You', genre: 'Animation', mood: 'Dreamy', description: 'A captivating romantic fantasy about love and weather.' },
  { id: 132, title: 'A Silent Voice', genre: 'Animation', mood: 'Moving', description: 'A thoughtful, emotional story about regret, forgiveness, and healing.' },
  { id: 133, title: 'Belle', genre: 'Animation', mood: 'Feel-good', description: 'A modern fairy tale of identity, self-expression, and belonging.' },
  { id: 134, title: 'Parasite', genre: 'Drama', mood: 'Sharp', description: 'An elegantly layered story of class, power, and survival.' },
  { id: 135, title: 'Memories of Murder', genre: 'Crime', mood: 'Gripping', description: 'A tense, human investigation story with haunting urgency.' },
  { id: 136, title: 'Oldboy', genre: 'Thriller', mood: 'Brutal', description: 'A raw and unforgettable revenge story with emotional depth.' },
  { id: 137, title: 'Train to Busan', genre: 'Action', mood: 'Tense', description: 'A high-speed survival film packed with urgency and heart.' },
  { id: 138, title: 'The Handmaiden', genre: 'Thriller', mood: 'Lush', description: 'A sensual and intricate thriller full of twists and atmosphere.' },
  { id: 139, title: 'Burning', genre: 'Mystery', mood: 'Tense', description: 'A slow-building mystery of obsession, longing, and ambiguity.' },
  { id: 140, title: 'Minari', genre: 'Drama', mood: 'Tender', description: 'A warm and earnest story about family, hope, and belonging.' },
  { id: 141, title: 'Shoplifters', genre: 'Drama', mood: 'Human', description: 'A intimate family drama about love in unconventional forms.' },
  { id: 142, title: 'Roma', genre: 'Drama', mood: 'Tender', description: 'A deeply lyrical portrait of family life and memory.' },
  { id: 143, title: 'Bicycle Thieves', genre: 'Drama', mood: 'Human', description: 'A classic story of poverty, dignity, and survival.' },
  { id: 144, title: 'Cinema Paradiso', genre: 'Drama', mood: 'Nostalgic', description: 'A heartfelt film about cinema, memory, and coming of age.' },
  { id: 145, title: 'The Lives of Others', genre: 'Drama', mood: 'Thoughtful', description: 'A layered and haunting story of surveillance and conscience.' },
  { id: 146, title: 'A Separation', genre: 'Drama', mood: 'Complex', description: 'A tense and morally layered exploration of family conflict.' },
  { id: 147, title: 'Amélie', genre: 'Romance', mood: 'Whimsical', description: 'A joyful, intimate portrait of romance and urban fantasy.' },
  { id: 148, title: 'Portrait of a Lady on Fire', genre: 'Romance', mood: 'Tender', description: 'A beautifully intense romance about love and artistic observation.' },
  { id: 149, title: 'Past Lives', genre: 'Romance', mood: 'Reflective', description: 'A subtle, emotional story about love, timing, and identity.' },
  { id: 150, title: 'Anora', genre: 'Comedy', mood: 'Wild', description: 'A bright, chaotic, and intimate story of connection and escape.' },
  { id: 151, title: 'The Big Short', genre: 'Comedy', mood: 'Sharp', description: 'A smart, funny film about finance, greed, and denial.' },
  { id: 152, title: 'The Wolf of Wall Street', genre: 'Comedy', mood: 'Wild', description: 'A ridiculous and over-the-top rise-and-fall saga.' },
  { id: 153, title: 'The Iron Giant', genre: 'Animation', mood: 'Heartfelt', description: 'A moving story about friendship and self-discovery.' },
  { id: 154, title: 'The Secret Life of Walter Mitty', genre: 'Adventure', mood: 'Dreamy', description: 'A whimsical adventure about wonder, courage, and reinvention.' },
  { id: 155, title: 'The Gentlemen', genre: 'Crime', mood: 'Sharp', description: 'A stylish crime comedy with wit, swagger, and menace.' },
  { id: 156, title: 'Klaus', genre: 'Animation', mood: 'Heartwarming', description: 'A visually inventive holiday tale of generosity and wonder.' },
  { id: 157, title: 'The Northman', genre: 'Action', mood: 'Dark', description: 'A grim and mythic revenge saga with brutal energy.' },
  { id: 158, title: 'The Green Knight', genre: 'Fantasy', mood: 'Mystical', description: 'A dreamlike and philosophical medieval fantasy.' },
  { id: 159, title: 'The Lighthouse', genre: 'Drama', mood: 'Haunting', description: 'A stark, eerie psychological drama set at sea.' },
  { id: 160, title: 'The Florida Project', genre: 'Drama', mood: 'Tender', description: 'A warm and observant portrait of childhood and resilience.' },
  { id: 161, title: 'Jeanne Dielman, 23, Quai du Commerce, 1080 Bruxelles', genre: 'Drama', mood: 'Minimal', description: 'A precise and human study of routine, labor, and quiet endurance.' },
  { id: 162, title: 'Nights of Cabiria', genre: 'Drama', mood: 'Poetic', description: 'A moving portrait of resilience and hope in difficult circumstances.' },
  { id: 163, title: 'The Color Purple', genre: 'Drama', mood: 'Emotional', description: 'A powerful and lyrical story about survival and sisterhood.' },
  { id: 164, title: 'Hachi: A Dog’s Tale', genre: 'Drama', mood: 'Heartwarming', description: 'A deeply sincere story of loyalty and love.' },
  { id: 165, title: 'The Pursuit of Happyness', genre: 'Drama', mood: 'Hopeful', description: 'A resilient and emotional story of determination and future.' },
  { id: 166, title: 'King Richard', genre: 'Drama', mood: 'Inspiring', description: 'A compelling story of grit, parenting, and ambitious greatness.' },
  { id: 167, title: 'The International', genre: 'Thriller', mood: 'Cerebral', description: 'A globe-spanning thriller of finance, power, and danger.' },
  { id: 168, title: 'The Equalizer', genre: 'Action', mood: 'Tough', description: 'A revenge-driven action film with steady, brutal intensity.' },
  { id: 169, title: 'The Nice Guys', genre: 'Comedy', mood: 'Funny', description: 'A clever and stylish detective comedy with layered energy.' },
  { id: 170, title: 'The Man from Earth', genre: 'Drama', mood: 'Thoughtful', description: 'A philosophical conversation film with a sharp central premise.' },
  { id: 171, title: 'The Last Emperor', genre: 'Drama', mood: 'Historical', description: 'A sweeping and intimate story of imperial history and identity.' },
  { id: 172, title: 'A Beautiful Mind', genre: 'Drama', mood: 'Inspirational', description: 'A moving story about brilliance, obsession, and recovery.' },
  { id: 173, title: 'The Royal Tenenbaums', genre: 'Comedy', mood: 'Quirky', description: 'A deadpan tragicomic story of family dysfunction and affection.' },
  { id: 174, title: 'O Brother, Where Art Thou?', genre: 'Comedy', mood: 'Adventure', description: 'A wisecracking odyssey with music, wit, and mythology.' },
  { id: 175, title: 'The Big Lebowski', genre: 'Comedy', mood: 'Laid-back', description: 'A cult classic of absurdity, style, and philosophical drift.' },
  { id: 176, title: 'The French Connection', genre: 'Crime', mood: 'Tense', description: 'A gritty urban thriller of pursuit, danger, and obsession.' },
  { id: 177, title: 'Unforgiven', genre: 'Western', mood: 'Grim', description: 'A measured, hard-hitting western about violence and conscience.' },
  { id: 178, title: 'The Good, the Bad and the Ugly', genre: 'Western', mood: 'Legendary', description: 'A classic western of tension, strategy, and legend.' },
  { id: 179, title: 'Django Unchained', genre: 'Western', mood: 'Explosive', description: 'A stylized revenge western with swagger and emotional force.' },
  { id: 180, title: 'The Searchers', genre: 'Western', mood: 'Classic', description: 'A towering western about obsession, loyalty, and frontier life.' },
  { id: 181, title: 'Y tu mamá también', genre: 'Drama', mood: 'Free-spirited', description: 'A road film of friendship, desire, and maturity.' },
  { id: 182, title: 'Roma', genre: 'Drama', mood: 'Tender', description: 'A portrait of family life and longing in a changing city.' },
  { id: 183, title: 'The Spirit of the Beehive', genre: 'Drama', mood: 'Poetic', description: 'A subtle and poetic story of childhood and imagination.' },
  { id: 184, title: 'City of God', genre: 'Crime', mood: 'Electric', description: 'A gritty and unforgettable portrait of urban life and violence.' },
  { id: 185, title: 'Central Station', genre: 'Drama', mood: 'Human', description: 'A moving journey of connection, memory, and migration.' },
  { id: 186, title: 'The Lives of Others', genre: 'Drama', mood: 'Thoughtful', description: 'A study of power, surveillance, and moral responsibility.' },
  { id: 187, title: 'The Diving Bell and the Butterfly', genre: 'Drama', mood: 'Beautiful', description: 'A visually striking story of perception, resilience, and imagination.' },
  { id: 188, title: 'The Theory of Everything', genre: 'Drama', mood: 'Inspirational', description: 'A touching story of intellect, love, and resilience.' },
  { id: 189, title: 'A Clockwork Orange', genre: 'Sci-Fi', mood: 'Disturbing', description: 'A dystopian critique of violence, free will, and control.' },
  { id: 190, title: 'The Hunger Games', genre: 'Action', mood: 'Intense', description: 'A fierce survival story of rebellion, spectacle, and pressure.' },
  { id: 191, title: 'Blade Runner', genre: 'Sci-Fi', mood: 'Atmospheric', description: 'A canon of noir sci-fi about humanity, memory, and identity.' },
  { id: 192, title: 'Eternal Sunshine of the Spotless Mind', genre: 'Romance', mood: 'Inventive', description: 'A surreal and tender meditation on memory and love.' },
  { id: 193, title: 'The Green Knight', genre: 'Fantasy', mood: 'Mystical', description: 'A mythic fantasy about masculinity, fate, and courage.' },
  { id: 194, title: 'I Am Sam', genre: 'Drama', mood: 'Heartfelt', description: 'A moving story about love, family, and dignity.' },
  { id: 195, title: 'The Secret in Their Eyes', genre: 'Mystery', mood: 'Intense', description: 'A sharp and emotional mystery about justice and memory.' },
  { id: 196, title: 'A Separation', genre: 'Drama', mood: 'Complex', description: 'A morally layered family tragedy about trust and duty.' },
  { id: 197, title: 'The Shape of Water', genre: 'Fantasy', mood: 'Romantic', description: 'A tender fantasy romance with a stunning sense of wonder.' },
  { id: 198, title: 'Le Fabuleux Destin d’Amélie Poulain', genre: 'Romance', mood: 'Whimsical', description: 'A joyful and imaginative story of love and coincidence.' },
  { id: 199, title: 'The Intouchables', genre: 'Comedy', mood: 'Uplifting', description: 'A warm and funny story about unlikely friendship.' },
  { id: 200, title: 'The Tragedy of Macbeth', genre: 'Drama', mood: 'Dark', description: 'A stark, dramatic retelling of ambition, fate, and guilt.' },
  { id: 201, title: 'The Fall', genre: 'Adventure', mood: 'Dreamlike', description: 'A visually rich fantasy of imagination and survival.' },
  { id: 202, title: 'The Fountain', genre: 'Drama', mood: 'Poetic', description: 'A meditative love story about time, mortality, and faith.' },
  { id: 203, title: 'The Neon Demon', genre: 'Thriller', mood: 'Hypnotic', description: 'A stylish and chilling look at beauty, envy, and desire.' },
  { id: 204, title: 'The Handmaiden', genre: 'Thriller', mood: 'Lush', description: 'A twisting and sensual mystery of deception and desire.' },
  { id: 205, title: 'Belfast', genre: 'Drama', mood: 'Warm', description: 'A nostalgic and intimate portrait of childhood amid conflict.' },
  { id: 206, title: 'All Quiet on the Western Front', genre: 'War', mood: 'Harsh', description: 'A devastating war film about fear, loss, and survival.' },
  { id: 207, title: '1917', genre: 'War', mood: 'Intense', description: 'A relentless war-time journey defined by urgency and fear.' },
  { id: 208, title: 'Saving Private Ryan', genre: 'War', mood: 'Brutal', description: 'A raw, devastating account of sacrifice in war.' },
  { id: 209, title: 'Dunkirk', genre: 'War', mood: 'Tense', description: 'A taut and immersive war film shaped by urgency and survival.' },
  { id: 210, title: 'The Patriot', genre: 'War', mood: 'Epic', description: 'A sweeping story of conflict, honour, and revolutionary struggle.' },
  { id: 211, title: 'The Inglorious Bastards', genre: 'War', mood: 'Wild', description: 'A violent and explosive revenge narrative set in wartime.' },
  { id: 212, title: 'The Hurt Locker', genre: 'War', mood: 'Intense', description: 'A high-pressure bomb disposal story about adrenaline and risk.' },
  { id: 213, title: 'The Great Dictator', genre: 'Comedy', mood: 'Satirical', description: 'A sharp, funny, and morally incisive satire.' },
  { id: 214, title: 'The Thin Red Line', genre: 'War', mood: 'Reflective', description: 'A meditative war film about fear, brotherhood, and mortality.' },
  { id: 215, title: 'The Deer Hunter', genre: 'Drama', mood: 'Haunting', description: 'A vivid and devastating portrait of war and aftermath.' },
  { id: 216, title: 'Nell', genre: 'Drama', mood: 'Tender', description: 'A compassionate story about language, connection, and belonging.' },
  { id: 217, title: 'The Secret of Karhyan', genre: 'Adventure', mood: 'Mystical', description: 'A mythic journey through wonder and courage.' },
  { id: 218, title: 'Kimi no Nawa', genre: 'Animation', mood: 'Romantic', description: 'A visually stunning story of connection, loss, and fate.' },
  { id: 219, title: 'Ghost in the Shell', genre: 'Animation', mood: 'Futuristic', description: 'A cerebral cyborg story about identity and consciousness.' },
  { id: 220, title: 'Akira', genre: 'Animation', mood: 'Revolutionary', description: 'A landmark cyberpunk anime with enormous influence and weight.' },
  { id: 221, title: 'Princess Mononoke', genre: 'Animation', mood: 'Epic', description: 'A mythic story of nature, humanity, and conflict.' },
  { id: 222, title: 'Howl’s Moving Castle', genre: 'Animation', mood: 'Dreamlike', description: 'A whimsical fantasy about magic, love, and transformation.' },
  { id: 223, title: 'Paprika', genre: 'Animation', mood: 'Surreal', description: 'A vivid, dreamlike dive into memory, imagination, and perception.' },
  { id: 224, title: 'The Wind Rises', genre: 'Animation', mood: 'Reflective', description: 'An elegant story of ambition, art, and historical change.' },
  { id: 225, title: 'The Boy and the Heron', genre: 'Animation', mood: 'Mystical', description: 'A visually rich story of grief, wonder, and emotional discovery.' },
  { id: 226, title: 'Chungking Express', genre: 'Drama', mood: 'Lyrical', description: 'A stylish and atmospheric portrait of urban longing and connection.' },
  { id: 227, title: 'In the Mood for Love', genre: 'Romance', mood: 'Tender', description: 'A luxurious, restrained love story of longing and missed chances.' },
  { id: 228, title: 'The Handmaiden', genre: 'Thriller', mood: 'Lush', description: 'A glamorous and intricate story of deception and desire.' },
  { id: 229, title: 'Evangelion: 3.0+1.0', genre: 'Animation', mood: 'Big', description: 'A huge, emotional finale of a deeply philosophical futuristic saga.' },
  { id: 230, title: 'The Match Factory Girl', genre: 'Drama', mood: 'Bleak', description: 'A sharp, intimate look at labour, loneliness, and emotional friction.' },
  { id: 231, title: 'Inside Llewyn Davis', genre: 'Drama', mood: 'Gritty', description: 'A folk-music story about ambition, failure, and artistic struggle.' },
  { id: 232, title: 'Mirrors', genre: 'Horror', mood: 'Claustrophobic', description: 'A suspenseful and unsettling story of obsession and reflection.' },
  { id: 233, title: 'The Wailing', genre: 'Horror', mood: 'Unsettling', description: 'A dense, eerie folk horror story of fear and infection.' },
  { id: 234, title: 'The Babadook', genre: 'Horror', mood: 'Heavy', description: 'A terrifying and emotional film about grief and trauma.' },
  { id: 235, title: 'The Menu', genre: 'Thriller', mood: 'Clever', description: 'A darkly funny and tense culinary thriller.' },
  { id: 236, title: 'Poor Things', genre: 'Fantasy', mood: 'Wild', description: 'A surreal and playful reimagining of identity and sexual freedom.' },
  { id: 237, title: 'The Favourite', genre: 'Drama', mood: 'Witty', description: 'A sharp, witty historical drama of power and intrigue.' },
  { id: 238, title: 'The Last Picture Show', genre: 'Drama', mood: 'Nostalgic', description: 'A tender portrait of adolescence, longing, and place.' },
  { id: 239, title: 'Lovers Rock', genre: 'Drama', mood: 'Warm', description: 'A music-filled story of love, escape, and connection.' },
  { id: 240, title: 'The Lodger', genre: 'Thriller', mood: 'Classic', description: 'A suspenseful and atmospheric early thriller.' },
  { id: 241, title: 'The Long Goodbye', genre: 'Crime', mood: 'Laid-back', description: 'A moody and witty noir with unconventional charm.' },
  { id: 242, title: 'The Conversation', genre: 'Thriller', mood: 'Observant', description: 'A suspenseful story about surveillance and paranoia.' },
  { id: 243, title: 'Murder on the Orient Express', genre: 'Mystery', mood: 'Classic', description: 'A locked-room mystery full of suspicion and twists.' },
  { id: 244, title: 'Knives Out', genre: 'Mystery', mood: 'Fun', description: 'A witty mystery with sharp twists and a big ensemble cast.' },
  { id: 245, title: 'The Girl with the Dragon Tattoo', genre: 'Mystery', mood: 'Dark', description: 'A grim mystery built on obsession, violence, and investigation.' },
  { id: 246, title: 'Gone Girl', genre: 'Mystery', mood: 'Tense', description: 'A razor-sharp thriller about media, marriage, and perception.' },
  { id: 247, title: 'The Talented Mr. Ripley', genre: 'Mystery', mood: 'Sleek', description: 'A seductive and chilling portrait of identity theft and obsession.' },
  { id: 248, title: 'The Invisible Guest', genre: 'Mystery', mood: 'Clever', description: 'A tightly wound thriller about guilt, lies, and a perfect alibi.' },
  { id: 249, title: 'A Prophet', genre: 'Crime', mood: 'Hard', description: 'A brutal prison drama about power, survival, and transformation.' },
  { id: 250, title: 'The Irishman', genre: 'Crime', mood: 'Measured', description: 'A long, reflective mob epic about memory, guilt, and consequence.' },
  { id: 251, title: 'Heat', genre: 'Crime', mood: 'Tense', description: 'A classic cat-and-mouse crime thriller with incredible precision.' },
  { id: 252, title: 'Dog Day Afternoon', genre: 'Crime', mood: 'Human', description: 'A tense and darkly comic story rooted in desperation and humanity.' },
  { id: 253, title: 'The Killing', genre: 'Crime', mood: 'Stylish', description: 'A noir crime film steeped in calculation and betrayal.' },
  { id: 254, title: 'The Long Good Friday', genre: 'Crime', mood: 'Dark', description: 'A brutal and vibrant London crime film.' },
  { id: 255, title: 'The Departed', genre: 'Crime', mood: 'Tense', description: 'A layered police-underworld thriller of paranoia and betrayal.' },
  { id: 256, title: 'A Beautiful Day in the Neighborhood', genre: 'Drama', mood: 'Warm', description: 'A gentle story about kindness, curiosity, and understanding.' },
  { id: 257, title: 'The Half of It', genre: 'Romance', mood: 'Tender', description: 'A nuanced coming-of-age romance about love and honesty.' },
  { id: 258, title: 'Call Me by Your Name', genre: 'Romance', mood: 'Tender', description: 'A languid and emotionally rich story of desire and self-discovery.' },
  { id: 259, title: 'Carol', genre: 'Romance', mood: 'Tender', description: 'A sumptuous and emotionally intense love story of longing and risk.' },
  { id: 260, title: 'Fleabag', genre: 'Comedy', mood: 'Witty', description: 'A sharp and vulnerable portrait of modern life and emotional messiness.' },
  { id: 261, title: 'The Farewell', genre: 'Drama', mood: 'Tender', description: 'A deeply human story of family, culture, and big feelings.' },
  { id: 262, title: 'Always Be My Maybe', genre: 'Comedy', mood: 'Warm', description: 'A witty, heart-filled romance about timing and second chances.' },
  { id: 263, title: 'Love, Simon', genre: 'Romance', mood: 'Warm', description: 'A heartfelt and open exploration of identity and love.' },
  { id: 264, title: 'The Kissing Booth', genre: 'Romance', mood: 'Fun', description: 'A breezy teen romance built on chemistry and chaos.' },
  { id: 265, title: 'The Notebook', genre: 'Romance', mood: 'Emotional', description: 'A sweeping love story with deep emotional weight.' },
  { id: 266, title: 'Titanic', genre: 'Romance', mood: 'Epic', description: 'A grand romantic tragedy set against a historic disaster.' },
  { id: 267, title: 'Moulin Rouge!', genre: 'Romance', mood: 'Musical', description: 'A vivid and exuberant musical about passion, art, and desire.' },
  { id: 268, title: 'The Greatest Showman', genre: 'Drama', mood: 'Inspiring', description: 'A show-stopping story about ambition, creativity, and spectacle.' },
  { id: 269, title: 'The Rocky Horror Picture Show', genre: 'Musical', mood: 'Wild', description: 'A campy cult classic with humour, music, and outrageous energy.' },
  { id: 270, title: 'La Bohème', genre: 'Drama', mood: 'Classic', description: 'A tender, atmospheric story of love and tragedy in Paris.' },
  { id: 271, title: 'The Last Samurai', genre: 'Action', mood: 'Epic', description: 'A sweeping tale of culture, honour, and transformation.' },
  { id: 272, title: 'Troy', genre: 'Action', mood: 'Epic', description: 'A sprawling mythic war epic of love, pride, and destiny.' },
  { id: 273, title: 'The Last Emperor', genre: 'Drama', mood: 'Historical', description: 'A richly cinematic portrait of empire and identity.' },
  { id: 274, title: 'The Patriot', genre: 'War', mood: 'Epic', description: 'A heroic story of family, conflict, and resistance.' },
  { id: 275, title: 'The Pianist', genre: 'War', mood: 'Intense', description: 'A devastating account of survival during the Holocaust.' },
  { id: 276, title: 'Apocalypto', genre: 'Adventure', mood: 'Brutal', description: 'A tense and immersive survival epic in the jungle.' },
  { id: 277, title: 'The Revenant', genre: 'Adventure', mood: 'Harsh', description: 'A brutal survival tale of revenge and endurance.' },
  { id: 278, title: 'The Tree of Life', genre: 'Drama', mood: 'Reflective', description: 'A meditative journey of childhood, grace, and meaning.' },
  { id: 279, title: 'Moonstruck', genre: 'Romance', mood: 'Warm', description: 'A funny and tender modern romance full of family and chaos.' },
  { id: 280, title: 'The Holiday', genre: 'Romance', mood: 'Warm', description: 'A charming and comforting story of second chances and holiday magic.' },
  { id: 281, title: 'Love Actually', genre: 'Romance', mood: 'Warm', description: 'A sprawling and charming tale of love across many lives.' },
  { id: 282, title: 'Notting Hill', genre: 'Romance', mood: 'Sweet', description: 'A delightful romantic comedy about chemistry and timing.' },
  { id: 283, title: 'The Proposal', genre: 'Comedy', mood: 'Light', description: 'A playful romantic comedy built on wit and tension.' },
  { id: 284, title: '50 First Dates', genre: 'Romance', mood: 'Sweet', description: 'A warm and humorous romance with heart and optimism.' },
  { id: 285, title: 'Crazy Rich Asians', genre: 'Romance', mood: 'Fun', description: 'A glossy and heartfelt comedy of wealth, family, and love.' },
  { id: 286, title: 'The Holiday Calendar', genre: 'Romance', mood: 'Merry', description: 'A cheerful holiday romance with magic and timing.' },
  { id: 287, title: 'Legally Blonde', genre: 'Comedy', mood: 'Funny', description: 'A witty and empowering story of confidence and reinvention.' },
  { id: 288, title: 'Mean Girls', genre: 'Comedy', mood: 'Sharp', description: 'A classic teen comedy about status, identity, and power.' },
  { id: 289, title: 'Clueless', genre: 'Comedy', mood: 'Playful', description: 'A stylish and witty coming-of-age comedy with iconic charm.' },
  { id: 290, title: 'Bridesmaids', genre: 'Comedy', mood: 'Wild', description: 'A sharp, hilarious look at friendship, love, and social pressure.' },
  { id: 291, title: 'The Hangover', genre: 'Comedy', mood: 'Chaotic', description: 'A chaotic and memorable bachelor comedy with endless energy.' },
  { id: 292, title: 'Superbad', genre: 'Comedy', mood: 'Chaotic', description: 'A funny and awkward high-school comedy about growing up.' },
  { id: 293, title: 'The Intern', genre: 'Comedy', mood: 'Warm', description: 'A charming workplace comedy about contrast, respect, and connection.' },
  { id: 294, title: 'The Intern', genre: 'Comedy', mood: 'Warm', description: 'A charming workplace comedy about contrast, respect, and connection.' },
  { id: 295, title: 'Chef', genre: 'Comedy', mood: 'Warm', description: 'A joyful food-centered story about second chances and identity.' },
  { id: 296, title: 'The Last King of Scotland', genre: 'Drama', mood: 'Intense', description: 'A politically charged and psychologically intense drama.' },
  { id: 297, title: 'The Founding Father', genre: 'Drama', mood: 'Historical', description: 'A serious and insightful look at power, leadership, and ideology.' },
  { id: 298, title: 'The Light Between Oceans', genre: 'Drama', mood: 'Emotional', description: 'A tender and haunting tale of love, guilt, and longing.' },
  { id: 299, title: 'The Fault in Our Stars', genre: 'Romance', mood: 'Emotional', description: 'A deeply heartfelt love story about life, loss, and meaning.' },
  { id: 300, title: 'A Walk to Remember', genre: 'Romance', mood: 'Tender', description: 'A sincere and heartfelt love story that leaves a lasting mark.' }
]

export const movieTitleSet = movieCatalog.map((movie) => movie.title)
export const movieTitlesByLanguage = {
  english: movieCatalog.map((movie) => movie.title),
  hindi: [
    '3 Idiots', 'Lagaan', 'Dangal', 'PK', 'Bajrangi Bhaijaan', 'Slumdog Millionaire', 'Gully Boy', 'RRR', 'Sholay', 'K.G.F: Chapter 1', 'Kabir Singh'
  ],
  japanese: ['Spirited Away', 'Your Name', 'Akira', 'Princess Mononoke', 'A Silent Voice', 'Howl’s Moving Castle', 'Kimi no Nawa'],
  korean: ['Parasite', 'Train to Busan', 'The Handmaiden', 'Oldboy', 'Memories of Murder', 'The Wailing', 'Burning'],
  french: ['Amélie', 'The Intouchables', 'Portrait of a Lady on Fire', 'Lovers Rock', 'Le Fabuleux Destin d’Amélie Poulain'],
  spanish: ['Roma', 'Y tu mamá también', 'The Spirit of the Beehive', 'The Secret in Their Eyes'],
  tamil: ['Baahubali: The Beginning', 'Baahubali 2: The Conclusion', 'K.G.F: Chapter 1', 'K.G.F: Chapter 2'],
  telugu: ['RRR', 'Baahubali: The Beginning', 'Baahubali 2: The Conclusion'],
  arabic: ['Theeb', 'Capernaum', 'Wadjda'],
  chinese: ['Crouching Tiger, Hidden Dragon', 'The Farewell', 'Yi Yi', 'Wong Kar-wai classics']
}
