export const openApiDocument = {
  openapi: '3.0.3',
  info: {
    title: 'ReelMates API',
    version: '1.2.0',
    description: 'ReelMates API (v1): daily films, film personality, film friends and opt-in dating. Authenticate with Bearer JWT from /auth/login or /auth/signup.'
  },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }
    }
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/health': { get: { summary: 'Health + DB probe', security: [] } },
    '/health/db': { get: { summary: 'Database health', security: [] } },
    '/health/storage': { get: { summary: 'Storage health', security: [] } },
    '/platform/version': { get: { summary: 'API + mobile version policy', security: [] } },
    '/platform/status': { get: { summary: 'Whether dating is open everywhere, and the public city board (percentages only)', security: [] } },
    '/auth/signup': { post: { summary: 'Register', security: [] } },
    '/auth/login': { post: { summary: 'Login', security: [] } },
    '/auth/forgot-password': { post: { summary: 'Request password reset', security: [] } },
    '/auth/reset-password': { post: { summary: 'Set a new password', security: [] } },
    '/auth/verify-email/confirm': { post: { summary: 'Confirm email token', security: [] } },
    '/auth/refresh': { post: { summary: 'Rotate refresh token', security: [] } },
    '/dating/undo': { post: { summary: 'Undo the last swipe unless it became a match' } },
    '/auth/logout': { post: { summary: 'Revoke refresh token' } },
    '/auth/me': { get: { summary: 'Current user + platform' } },
    '/movies/daily': { get: { summary: 'Daily taste game films' } },
    '/movies/{id}/rate': { post: { summary: 'Rate film love/hate/skip' } },
    '/dating/deck': { get: { summary: 'Next dating profile + meta' } },
    '/dating/swipe': { post: { summary: 'Like or pass profile' } },
    '/dating/matches': { get: { summary: 'Mutual matches' } },
    '/movies/daily/results': { get: { summary: "Today's films with your votes and everyone's, plus a shareable result line" } },
    '/dating/likes-you': { get: { summary: 'People who liked you: count for everyone, profiles with ReelMates Plus' } },
    '/platform/status/me': { get: { summary: "Is dating open for the signed-in member, and their city's progress" } },
    '/messages/{userId}/starters': { get: { summary: 'Conversation starters for a match, from shared films and prompts' } },
    '/users/taste-card': { put: { summary: 'Make your public taste card visible or hidden ({ public })' } },
    '/public/taste/{code}': { get: { summary: 'Public taste card by friend code (only when shared)', security: [] } },
    '/billing/revenuecat': { post: { summary: 'RevenueCat webhook (Authorization: REVENUECAT_WEBHOOK_AUTH)', security: [] } },
    '/dating/referral': { get: { summary: 'Referral code' } },
    '/messages/conversations': { get: { summary: 'Inbox list' } },
    '/messages/{userId}': { get: { summary: 'Thread messages (optional ?since=ISO)' } },
    '/messages/{userId}/read': { post: { summary: 'Mark peer messages read' } },
    '/messages': { post: { summary: 'Send message' } },
    '/users/profile': { get: { summary: 'Profile' }, put: { summary: 'Update profile + discovery prefs' } },
    '/users/profile/completeness': { get: { summary: 'Profile completion gate' } },
    '/users/avatar': { post: { summary: 'Upload avatar (base64)' } },
    '/movies/search': { get: { summary: 'Search films by title (?q=), with your rating' } },
    '/movies/top': { get: { summary: "People's chart: films ranked by community likes (?collection=)" } },
    '/movies/collections': { get: { summary: 'Film collections with counts' } },
    '/users/favorite': { put: { summary: 'Set or clear your all-time favourite film ({ movieId })' } },
    '/users/taste-stats': { get: { summary: 'Your taste stats (genres, languages, decades)' } },
    '/friends': { get: { summary: 'Film friends with taste match, and your friend code' }, post: { summary: 'Add a friend by code ({ code })' } },
    '/friends/{userId}': { delete: { summary: 'Remove a film friend' } },
    '/friends/compare/{userId}': { get: { summary: 'Compare taste and get watch-together ideas (friend or match)' } },
    '/feedback': { post: { summary: 'Send feedback ({ category: bug|idea|film|other, message })' } },
    '/admin/feedback': { get: { summary: 'Feedback inbox (x-admin-key, ?status=new|read|done)' } },
    '/notifications/register': { post: { summary: 'Register Expo push token' } },
    '/safety/block': { post: { summary: 'Block user' } },
    '/safety/report': { post: { summary: 'Report user (reason: spam|harassment|fake_profile|inappropriate|other; block?: boolean)' } },
    '/safety/account': { delete: { summary: 'Delete account' } },
    '/admin/moderation/queue': { get: { summary: 'Moderation queue (x-admin-key)' } },
    '/admin/moderation/{id}': { patch: { summary: 'Update moderation item' } },
    '/admin/users/{userId}/verification': { patch: { summary: 'Mark a profile verified (shows a verified tag)' } },
    '/admin/platform': {
      get: { summary: 'City launch: settings and every city with counts (x-admin-key)' },
      patch: { summary: 'Set the city target, open cities by hand, or open/close everywhere ({ cityTarget, openCities, datingOpen })' }
    },
    '/admin/users/{userId}/suspension': { patch: { summary: 'Suspend or restore an account ({ suspended, reason })' } },
    '/internal/daily-reminders': { post: { summary: 'Cron: daily game push (x-cron-secret)' } },
    '/internal/inactivity-cleanup': { post: { summary: 'Cron: pause inactive matchmaking (x-cron-secret)' } }
  }
}
